config: typo and rmv Marco Acorte’s list because redundant
serverless-dns/blocklists pull request #125
Opened 2023-01-09 00:21 UTC by GiddyGoatGaming

Marco Acorte’s list is already included in Hagezi’s threat intelligence so keeping it alongside is redundant

2023-01-10 12:14 UTC, ignoramous requested changes

2023-01-10 12:14 UTC, ignoramous commented on config.json
> +      "format": "hosts",
I see domains in the `url` not hosts...?

2023-01-10 12:27 UTC, GiddyGoatGaming commented on config.json
> +      "format": "hosts",
> I see domains in the `url` not hosts...?

This is the thing you said to leave at hosts here https://github.com/serverless-dns/blocklists/pull/121#discussion_r1064004539 .

2023-01-10 16:40 UTC, ignoramous commented on config.json
> +      "format": "hosts",
oh its a mix? That's fine... I am dog chasing my own tail, wouldn't you know ;)

2023-01-10 16:53 UTC, GiddyGoatGaming commented on config.json
> +      "format": "hosts",
> oh this list is a mix? That's fine... I am a dog chasing my own tail, wouldn't you know ;)

🤣

2023-01-11 20:45 UTC, ignoramous commented on config.json
> -        "https://raw.githubusercontent.com/marco-acorte/antispam-it/main/antispam-it.txt",
We can leave it up in case Hagezi's lists alllowlist / whitelist a domain?

2023-01-11 20:46 UTC, ignoramous commented on config.json
> +        "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei.txt"],
Why Huawei in Xiaomi entry? Mistyped?

2023-01-11 20:53 UTC, GiddyGoatGaming commented
Sorry about all that, I got confused between huawei and xiaomi (i always have, Both are Chinese phone companies🤣). I moved the hagezi huawei list into the huawei list and moved back the xiaomi list. And I added back Marco’s list👍

2023-01-12 00:28 UTC, ignoramous commented on config.json
> +      "format": ["wildcard", "hosts"],
missing corresponding entry here. possibly, `"domains"`?

2023-01-12 01:32 UTC, GiddyGoatGaming commented on config.json
> +      "format": ["wildcard", "hosts"],
> missing corresponding entry here. possibly, `"domains"`?

Nice eye👀. Also, I haven’t made this many mistakes adding/switching lists since my first commit for this repo. I’m so disappointed in myself😂

2023-01-12 02:06 UTC, ignoramous commented on config.json
> +      "format": ["wildcard", "hosts"],
That's okay. Don't fret about it. There aren't tests here and this work is rote and manual. Happens more often than you think and never gets any more error-free with time or anything.

2023-01-12 02:27 UTC, ignoramous approved these changes

2023-01-12 02:30 UTC, merged

2023-01-12 02:33 UTC, GiddyGoatGaming commented
Thanks!