Add Badware Holster & Use Proper Spelling For HaGeZi
serverless-dns/blocklists pull request #154
Opened 2023-05-09 15:00 UTC by SpencerIsGiddy

Adds Hagezi's Badware Holster list and uses the proper spelling for HaGeZi.

Hagezi -> HaGeZi

2023-05-09 18:55 UTC, ignoramous commented on config.json
> +      "vname": "Badware Holster",
Could this list be merged with an existing one? Hagezi's lists are usually a combo of other lists, so there might already exist an entry that might suit this merger?

2023-05-09 18:55 UTC, ignoramous commented on config.json
> +      "vname": "Ultimate (HaGeZi)",
Ah! Thanks (:

2023-05-09 19:11 UTC, SpencerIsGiddy commented on config.json
> +      "vname": "Badware Holster",
I can’t find any current list that uses any of the [sources](https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#hoster) so I would say it can be used seperately.

2023-05-09 21:11 UTC, ignoramous commented on config.json
> +      "vname": "Badware Holster",
Makes sense. I spot a `dead` list viz. `Malware (azorult-tracker.net)`. What do you think about adding this one as a replacement for it?

2023-05-09 21:30 UTC, SpencerIsGiddy commented on config.json
> +      "vname": "Badware Holster",
Sounds good to me👍

2023-05-13 12:35 UTC, ignoramous requested changes
forgot to publish the comment :facepalm:

2023-05-13 22:52 UTC, ignoramous approved these changes

2023-05-13 22:52 UTC, merged